add_lunch_combo lineage_herolte-eng
add_lunch_combo lineage_herolte-userdebug
add_lunch_combo lineage_herolte-user

add_lunch_combo aicp_herolte-eng
add_lunch_combo aicp_herolte-userdebug
add_lunch_combo aicp_herolte-user

add_lunch_combo aokp_herolte-eng
add_lunch_combo aokp_herolte-userdebug
add_lunch_combo aokp_herolte-user

add_lunch_combo aosp_herolte-eng
add_lunch_combo aosp_herolte-userdebug
add_lunch_combo aosp_herolte-user

add_lunch_combo gzosp_herolte-eng
add_lunch_combo gzosp_herolte-userdebug
add_lunch_combo gzosp_herolte-user

add_lunch_combo omni_herolte-eng
add_lunch_combo omni_herolte-userdebug
add_lunch_combo omni_herolte-user

add_lunch_combo rr_herolte-eng
add_lunch_combo rr_herolte-userdebug
add_lunch_combo rr_herolte-user

add_lunch_combo du_herolte-eng
add_lunch_combo du_herolte-userdebug
add_lunch_combo du_herolte-user
